### ISSUE TITLE
Session - cookie domain and path auto configuration

### ISSUE THREAD

**Issue by mabar** [nette/http#163]
In nette 2.4 it was possible to auto-configure session domain and path from current request. With deprecated support for `?` in config it is no longer possible to do.

```yaml
session:
    cookieDomain: '?->getUrl()->getDomain(2)'(@Nette\Http\IRequest)
    cookiePath: '?->getUrl()->getBasePath()'(@Nette\Http\IRequest)
```

Suggested solution:
Add values `domain` and `subdomain` for `cookieDomain` and `auto` for `cookiePath`

Naming for `cookieDomain` should be discussed - possible behaviors are - subdomain specific (`foo.example.com`), whole domain (`*.example.com`) and maybe also domain only, without subdomains? (`example.com`)

`auto` value for `cookiePath` can be potentially colliding with requirement for `auto` as a static base path - but I don't see a real, problematic use-case, which would need it.

I can send PR, if you agree with that feature.
